# -*- coding: utf-8 -*-
"""EmailSender.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Be_5k1vfCM--ObeBX_WHA_Zv8EAQ1e6T
"""

!pip install schedule

import smtplib
import ssl
import csv
import os
import time
import schedule
from getpass import getpass  # Securely input password in Colab
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from google.colab import drive
drive.mount('/content/drive')

# --- USER CONFIGURATION ---
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 465
# Base path for your project files in Google Drive
DRIVE_PROJECT_PATH = '/content/drive/MyDrive/EmailProjectFiles/'

if not os.path.exists(DRIVE_PROJECT_PATH):
    print(f"Error: Drive folder not found at {DRIVE_PROJECT_PATH}. Please check the path.")

# Full file paths
CONTACTS_FILE = os.path.join(DRIVE_PROJECT_PATH, 'contacts.csv')
ATTACHMENT_FILE = os.path.join(DRIVE_PROJECT_PATH, 'document.pdf') # Must match the file name in your Drive folder

# Securely input credentials
SENDER_EMAIL = input("Enter your Gmail Address: ")
SENDER_PASSWORD = getpass("Enter App Password: ") # Input is hidden #You'll need your Gmail App Password (the 16-character code) from your Google Account security settings

def send_email(recipient_name, recipient_email):
    """Constructs and sends an email with an attachment."""
    try:
        # 1. Setup the MIME Object
        msg = MIMEMultipart()
        msg['From'] = SENDER_EMAIL
        msg['To'] = recipient_email
        msg['Subject'] = f"Automated Colab Report for {recipient_name}"

        # 2. Create the Body
        body = f"Hi {recipient_name},\n\nThis is a batch test sent from Colab, reading files directly from Google Drive!"
        msg.attach(MIMEText(body, 'plain'))

        # 3. Handle Attachment
        if os.path.exists(ATTACHMENT_FILE):
            with open(ATTACHMENT_FILE, "rb") as attachment:
                part = MIMEBase('application', 'octet-stream') # Fixed typo: MIMEMase -> MIMEBase
                part.set_payload(attachment.read())

            encoders.encode_base64(part)
            filename = os.path.basename(ATTACHMENT_FILE)
            part.add_header("Content-Disposition", f"attachment; filename= {filename}")
            msg.attach(part)
        else:
            print(f"Warning: Attachment {ATTACHMENT_FILE} not found in Drive. Sending without it.")

        # 4. Connect to Server and Send
        context = ssl.create_default_context()
        with smtplib.SMTP_SSL(SMTP_SERVER, SMTP_PORT, context=context) as server:
            server.login(SENDER_EMAIL, SENDER_PASSWORD)
            server.sendmail(SENDER_EMAIL, recipient_email, msg.as_string())

        print(f"✅ Email sent successfully to {recipient_name}")

    except Exception as e:
        print(f"Failed to send to {recipient_email}. Error: {e}")

def batch_job():
    """Reads the CSV from Google Drive and triggers the send_email function."""
    print("\n--- Starting Colab Batch Job (Reading from Drive) ---")
    if not os.path.exists(CONTACTS_FILE):
        print(f"Critical Error: contacts.csv not found at {CONTACTS_FILE}. Check the file name and path.")
        return

    with open(CONTACTS_FILE, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header

        for row in reader:
            if row and len(row) >= 2: # Ensure the row is not empty and has at least two columns
                name, email = row[0], row[1]
                send_email(name, email)
                time.sleep(1)
            else:
                print(f"Warning: Skipping malformed row: {row}") # Add a warning for skipped rows
    print("--- Batch Job Complete ---\n")

# --- EXECUTION ---
# Run the job immediately to test the secure connection and file paths
batch_job()