# -*- coding: utf-8 -*-
"""Personal Budget Tracker Program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kl7HOVWhj7PVWCg_OhBHlofyrXSRR-yR
"""

import csv
from datetime import datetime
import os

# --- Helper Functions (Revised) ---

def get_expense_input():
    """
    Prompts the user for expense name and amount and returns them.
    Handles input validation for the amount AND checks for the 'done' command
    immediately after the name is entered.
    """
    while True:
        # 1. Prompt for the expense name
        name = input("Enter expense name (e.g., Groceries): ").strip()

        # --- NEW LOGIC: Check for the stop word immediately after name input ---
        if name.lower() == 'done':
            # Special return to signal the main loop to stop
            return 'done', 0
        # ---------------------------------------------------------------------

        if not name:
            print("Expense name cannot be empty. Please try again.")
            continue

        # 2. Prompt for the expense amount and validate it
        while True:
            amount_str = input(f"Enter amount for '{name}' (e.g., 50.50): ").strip()

            # We no longer need to check for 'done' here, but we'll keep
            # the input validation clean.
            try:
                # Convert input to a float and ensure it's positive
                amount = float(amount_str)
                if amount <= 0:
                    print("Amount must be a positive number. Please try again.")
                    continue
                return name, amount
            except ValueError:
                print("Invalid amount. Please enter a valid number.")

# --- Other Functions (Unchanged) ---

def collect_expenses():
    """
    Collects expenses from the user until they enter 'done'.
    Stores them in a dictionary.
    """
    print("\n--- Expense Input ---")
    print("Enter 'done' at the **expense name** prompt to stop entering expenses.")

    expenses = {}
    expense_count = 1

    while True:
        print(f"\nExpense #{expense_count}")
        name, amount = get_expense_input()

        # Check for the stop condition passed back from get_expense_input
        if name == 'done':
            break

        expenses[expense_count] = {'name': name, 'amount': amount}
        expense_count += 1

    return expenses

def calculate_stats(expenses_dict):
    """
    Calculates total, average, highest, and lowest expenses.
    Returns the results in a dictionary.
    """
    amounts = [data['amount'] for data in expenses_dict.values()]

    if not amounts:
        return {
            'total': 0,
            'average': 0,
            'highest': ('N/A', 0),
            'lowest': ('N/A', 0)
        }

    total_expenses = sum(amounts)
    average_expense = total_expenses / len(amounts)

    highest_amount = max(amounts)
    lowest_amount = min(amounts)

    highest_expense = next(
        (data['name'], data['amount'])
        for data in expenses_dict.values()
        if data['amount'] == highest_amount
    )
    lowest_expense = next(
        (data['name'], data['amount'])
        for data in expenses_dict.values()
        if data['amount'] == lowest_amount
    )

    return {
        'total': total_expenses,
        'average': average_expense,
        'highest': highest_expense,
        'lowest': lowest_expense
    }

def print_results(stats):
    """
    Prints the calculated financial statistics in a formatted way.
    """
    print("\n--- Budget Summary ---")
    print(f"Total Expenses: ${stats['total']:.2f}")
    print(f"Average Expense: ${stats['average']:.2f}")

    highest_name, highest_amount = stats['highest']
    lowest_name, lowest_amount = stats['lowest']

    print(f"Highest Expense: {highest_name} (${highest_amount:.2f})")
    print(f"Lowest Expense: {lowest_name} (${lowest_amount:.2f})")
    print("----------------------")

def save_results(stats):
    """
    Saves the calculated statistics to a text file.
    """
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"budget_summary_{timestamp}.txt"

    try:
        with open(filename, 'w') as f:
            f.write("Personal Budget Tracker Results\n")
            f.write("--------------------------------\n")
            f.write(f"Total Expenses: ${stats['total']:.2f}\n")
            f.write(f"Average Expense: ${stats['average']:.2f}\n")

            highest_name, highest_amount = stats['highest']
            lowest_name, lowest_amount = stats['lowest']

            f.write(f"Highest Expense: {highest_name} (${highest_amount:.2f})\n")
            f.write(f"Lowest Expense: {lowest_name} (${lowest_amount:.2f})\n")
            f.write("--------------------------------\n")

        print(f"\nResults successfully saved to **{filename}**")
        print(f"The file is located in: **{os.path.abspath(filename)}**")

    except IOError:
        print(f"\nERROR: Could not write to the file {filename}")

# --- Main Program Execution ---

def main():
    """
    The main function to run the entire budget tracking program.
    """
    print("Welcome to the Personal Budget Tracker!")

    # 1. Collect user input and store in a dictionary
    all_expenses = collect_expenses()

    if not all_expenses:
        print("\nNo expenses were entered. Exiting program.")
        return

    # 2. Calculate the required statistics
    expense_stats = calculate_stats(all_expenses)

    # 3. Print the results to the console
    print_results(expense_stats)

    # 4. Save the results to a text file
    save_results(expense_stats)

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive')