# -*- coding: utf-8 -*-
"""file_organizer.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hr6pvsPo82rxFMeQE5WYNWj_qqHsYpT8
"""

import os
import shutil
import re
from datetime import datetime

# --- Configuration ---
# Define file extensions and the corresponding folder names
FILE_TYPES = {
    "Images": ['.jpg', '.jpeg', '.png', '.gif', '.bmp', '.tiff'],
    "Documents": ['.pdf', '.doc', '.docx', '.txt', '.xlsx', '.pptx', '.csv'],
    "Videos": ['.mp4', '.mov', '.avi', '.mkv', '.webm'],
    "Audio": ['.mp3', '.wav', '.flac', '.aac'],
    "Archives": ['.zip', '.rar', '.7z', '.tar', '.gz'],
    "Code": ['.py', '.js', '.html', '.css', '.java', '.c', '.cpp'],
    "Other": [] # Default category for unlisted files
}

# The folder to organize (use '.' for the current directory where the script is run)
TARGET_DIR = '.'

# The name of the log file
LOG_FILE_NAME = "file_organization_log.txt"

# --- Utility Functions ---

def clean_filename(filename):
    """
    Renames a file to be consistent by:
    1. Replacing spaces with underscores.
    2. Removing any characters that are not letters, numbers, hyphens, underscores, or periods.
    """
    name, ext = os.path.splitext(filename)

    # Replace spaces and hyphens with a single underscore
    cleaned_name = re.sub(r'[ -]+', '_', name)

    # Remove any characters that are not alphanumeric or underscore
    cleaned_name = re.sub(r'[^\w_]', '', cleaned_name)

    # Ensure no leading/trailing underscores
    cleaned_name = cleaned_name.strip('_')

    # Reassemble the name
    if not cleaned_name:
        return filename # Fallback if cleaning results in an empty string

    return f"{cleaned_name}{ext.lower()}"

def get_file_type(extension):
    """Determines the correct folder name for a given file extension."""
    extension = extension.lower()
    for folder, extensions in FILE_TYPES.items():
        if extension in extensions:
            return folder
    return "Other"

# --- Main Organization Logic ---

def organize_files(target_dir=TARGET_DIR, create_log=True):
    """
    Main function to organize files in the specified directory.
    """
    print(f"🚀 Starting file organization in: {os.path.abspath(target_dir)}")
    log_entries = []

    if create_log:
        log_entries.append(f"--- File Organization Log - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} ---")

    # Iterate over all items in the target directory
    for item in os.listdir(target_dir):
        # Skip the log file and directories
        if item == LOG_FILE_NAME or os.path.isdir(os.path.join(target_dir, item)):
            continue

        source_path = os.path.join(target_dir, item)

        # 1. Rename File for Consistency
        new_name = clean_filename(item)
        temp_path = source_path # Start with the original path

        if new_name != item:
            # Rename the file if it needs cleaning
            temp_path = os.path.join(target_dir, new_name)
            try:
                os.rename(source_path, temp_path)
                log_entries.append(f"RENAMED: '{item}' -> '{new_name}'")
                print(f"  -> Renamed: {item} to {new_name}")
            except OSError as e:
                # Handle case where the target name already exists
                log_entries.append(f"ERROR: Could not rename '{item}' to '{new_name}'. Skipping move. Error: {e}")
                print(f"  -> ERROR: Could not rename {item}. Skipping move.")
                continue # Skip the rest of the loop for this file

        # 2. Move File into Subfolder

        # Get the extension and destination folder
        _, ext = os.path.splitext(new_name)
        destination_folder = get_file_type(ext)
        destination_path = os.path.join(target_dir, destination_folder)

        # Create the destination folder if it doesn't exist
        if not os.path.exists(destination_path):
            os.makedirs(destination_path)
            log_entries.append(f"CREATED: Folder '{destination_folder}'")

        # Move the file
        final_destination_path = os.path.join(destination_path, new_name)
        try:
            shutil.move(temp_path, final_destination_path)
            log_entries.append(f"MOVED: '{new_name}' -> '{destination_folder}/'")
            print(f"  -> Moved: {new_name} to {destination_folder}/")
        except shutil.Error as e:
            log_entries.append(f"ERROR: Could not move '{new_name}'. Error: {e}")
            print(f"  -> ERROR: Could not move {new_name}")

    # 3. Create Log File (Optional)
    if create_log:
        try:
            with open(os.path.join(target_dir, LOG_FILE_NAME), 'a') as f:
                f.write('\n'.join(log_entries) + '\n\n')
            print(f"\n✅ Organization complete. Log saved to {LOG_FILE_NAME}")
        except IOError:
            print("\n❌ Organization complete, but could not write to log file.")
    else:
        print("\n✅ Organization complete. No log file created.")

# --- Execution ---

if __name__ == "__main__":
    # You can change 'True' to 'False' below if you don't want a log file
    organize_files(create_log=True)